### ISSUE TITLE
I am afraid you use labels of unlabeled data point 

### ISSUE THREAD

**Issue by pengxiao-song** [jifanz/GALAXY#1]
Hello, thank you for your nice work! 
But I have one question about the implementation of GALAXY as follows:

**Why can you use labels of unlabeled data point in** `(n1.label == n2.label)` ?

This makes me a little confused, so could you make an explanation? THANKS!

```Python
@staticmethod
def check_add_neighbor(n1: Node, n2: Node, graph: Graph):
    if (n1.label == n2.label) or (not n1.queried) or (not n2.queried):
        n1.add_neighbors([n2])
        if n1.idx < n2.idx:
            graph.edges.add((n1, n2))
```
[https://github.com/jifanz/GALAXY/blob/main/src/graph.py#L177](https://github.com/jifanz/GALAXY/blob/main/src/graph.py#L177)

**Comment by jifanz** [comment]
I think the logic here is if any of the two nodes are unlabeled OR both are labeled and their labels are equal, I insert as neighbor. This is equivalent with ```not (n1.queried and n2.queried and n1.label != n2.label)```.

**Comment by pengxiao-song** [comment]
> I think the logic here is if any of the two nodes are unlabeled OR both are labeled and their labels are equal, I insert as neighbor. This is equivalent with `not (n1.queried and n2.queried and n1.label != n2.label)`.

I agree with you, but I think the original code should be
 `if (not n1.queried) or (not n2.queried) or (n1.queried and n2.queried and n1.label == n2.label)`, 
rather than 
`if (n1.label == n2.label) or (not n1.queried) or (not n2.queried)`.

Because I think the latter implementation means that we have always known a data point's label whether or not it has been queried.

**Comment by jifanz** [comment]
Logic conjunctions are commutative: https://en.wikipedia.org/wiki/Commutativity_of_conjunction

This statement is saying I'm NOT going to connect neighbors only when both are queried AND their labels are equal. Otherwise, I will connect the neighbors anyways. You can check the validity by laying out a truth table. The if statement will evaluate to be false only when the above mentioned criterions are satisfied (n1.label != n2.label, n1.queried, n2.queried).

Note the lazy evaluation rule for python does not change the meaning of the statement. The two different orders you mentioned above do not change what the statement evaluates to.

**Comment by pengxiao-song** [comment]
> Logic conjunctions are commutative: https://en.wikipedia.org/wiki/Commutativity_of_conjunction
> 
> This statement is saying I'm NOT going to connect neighbors only when both are queried AND their labels are equal. Otherwise, I will connect the neighbors anyways. You can check the validity by laying out a truth table. The if statement will evaluate to be false only when the above mentioned criterions are satisfied (n1.label != n2.label, n1.queried, n2.queried).
> 
> Note the lazy evaluation rule for python does not change the meaning of the statement. The two different orders you mentioned above do not change what the statement evaluates to.

I understand what this statement means. The implementation `if (n1.label == n2.label) or (not n1.queried) or (not n2.queried)` allows (n1.label == n2.label, not n1.queried, not n2.queried) to pass, but I think this situation is illegal because we get the labels of n1 and n2 when they haven't been queried.

**Comment by jifanz** [comment]
Put aside if I'm using the label of a node even when it's not queried. Do you think the two statements
```
(not n1.queried) or (not n2.queried) or (n1.label == n2.label)
```
and 
```
(n1.label == n2.label) or (not n1.queried) or (not n2.queried)
```
are equivalent logically?

Is the first statement above "legal" by your definition?

My code may be using the label of an unlabeled node, but its equivalent meaning doesn't. So when an equivalent logical statement with the same meaning is "legal" by your definition, what makes you think this statement to be "illegal"? They have the exact same meaning.

**Comment by pengxiao-song** [comment]
> Put aside if I'm using the label of a node even when it's not queried. Do you think the two statements
> 
> ```
> (not n1.queried) or (not n2.queried) or (n1.label == n2.label)
> ```
> 
> and
> 
> ```
> (n1.label == n2.label) or (not n1.queried) or (not n2.queried)
> ```
> 
> are equivalent logically?
> 
> Is the first statement above "legal" by your definition?
> 
> My code may be using the label of an unlabeled node, but its equivalent meaning doesn't. So when an equivalent logical statement with the same meaning is "legal" by your definition, what makes you think this statement to be "illegal"? They have the exact same meaning.

**Do you agree with that you use the label of a node which it's not queried?**

I don't think the two statements are equivalent because of lazy evaluation rule.

**Comment by jifanz** [comment]
If they are not equivalent, can you give me a case where the first will evaluate to a different result than the second.

I’m arguing that the interpretation of this implementation does NOT use the label of unlabeled nodes. It doesn’t matter how I implement it as long as it achieves the same meaning.

Also, please find a second pair of eyes, preferably your advisor. Feel free to email me if you both think this is problematic. This is my last comment here as I do not see a problem with the implementation.

**Comment by jifanz** [comment]
Just for reference, here's the truth table that shows the two statements are equivalent:

| n1.label==n2.label | n1.queried | n2.queried | (not n1.queried) or (not n2.queried) or (n1.label == n2.label) | (n1.label == n2.label) or (not n1.queried) or (not n2.queried)|
| ------------- | ------------- | ------------- | ------------- | ------------- |
| True | True | True | True | True |
| True | True | False | True | True |
| True | False | True | True | True |
| True | False | False | True | True |
| False | True | True | False | False |
| False | True | False | True | True |
| False | False | True | True | True |
| False | False | False | True | True |

As a result, the two statements are equivalent lines of code and would evaluate the same result. Since
```
(not n1.queried) or (not n2.queried) or (n1.label == n2.label)
```
clearly doesn't use the labels of the labels of unlabeled examples, 
```
(n1.label == n2.label) or (not n1.queried) or (not n2.queried)
```
is not using labels of a node by equivalent interpretation.

The issue raised is based on a misunderstanding that lazy evaluation changes the logical meaning (i.e. outcome) of conjunction expressions, which is clearly wrong.

**Comment by pengxiao-song** [comment]
> Just for reference, here's the truth table that shows the two statements are equivalent:
> 
> n1.label==n2.label	n1.queried	n2.queried	(not n1.queried) or (not n2.queried) or (n1.label == n2.label)	(n1.label == n2.label) or (not n1.queried) or (not n2.queried)
> True	True	True	True	True
> True	True	False	True	True
> True	False	True	True	True
> True	False	False	True	True
> False	True	True	False	False
> False	True	False	True	True
> False	False	True	True	True
> False	False	False	True	True
> As a result, the two statements are equivalent lines of code and would evaluate the same result. Since
> 
> ```
> (not n1.queried) or (not n2.queried) or (n1.label == n2.label)
> ```
> 
> clearly doesn't use the labels of the labels of unlabeled examples,
> 
> ```
> (n1.label == n2.label) or (not n1.queried) or (not n2.queried)
> ```
> 
> is not using labels of a node by equivalent interpretation.
> 
> The issue raised is based on a misunderstanding that lazy evaluation changes the logical meaning (i.e. outcome) of conjunction expressions, which is clearly wrong.

The issue raised is based on 
`(not n1.queried) or (not n2.queried) or (n1.label == n2.label)`
is not equivalent with
`(not n1.queried) or (not n2.queried) or (n1.queried and n2.queried and n1.label == n2.label)` 

The condition `n1.label == n2.label` comes from the premise `(n1.queried and n2.queried)`

**Comment by jifanz** [comment]
No, you are saying there exists values of A, B and C so that
```
A or B or C  != B or C or A
```
This is clearly wrong. Now, if they are always equal, you can always substitute one way of writing it with another. Please learn logical statements in python again... You are fundamentally wrong on this. Lazy evaluation is not designed for changing the meaning in any ways. It only matters if one way of writing it throws an exception.

**Comment by pengxiao-song** [comment]
> No, you are saying there exists values of A, B and C so that
> 
> ```
> A or B or C  != B or C or A
> ```
> 
> This is clearly wrong. Now, if they are always equal, you can always substitute one way of writing it with another. Please learn logical statements in python again... You are fundamentally wrong on this. Lazy evaluation is not designed for changing the meaning in any ways. It only matters if one way of writing it throws an exception.

From the very beginning, I had raised my confusion:
![image](https://user-images.githubusercontent.com/47233927/205474098-e6f86aec-4b44-4439-b379-bd13d6c6d72c.png)

After that, maybe sometimes I misunderstood your meaning. Obviously, Your answer about logic statements is well acknowledged and I agree with that for sure.

BUT Now, **I am saying** my original opinion again:
![image](https://user-images.githubusercontent.com/47233927/205475138-bcd08b68-ea12-4714-afda-07b09b588310.png)

So, could you face the **real** problem and clear up my confusion? Thank you!

**Comment by jifanz** [comment]
Sorry I didn’t see your edits after our initial conversation. These two are also logically equivalent.
A or B or C = A or B or (not A and not B and C)

You can write out a truth table for it.

**Comment by pengxiao-song** [comment]
> Sorry I didn’t see your edits after our initial conversation. These two are also logically equivalent. A or B or C = A or B or (not A and not B and C)
> 
> You can write out a truth table for it.

I made some edits.

Now, put aside abstract statement of 'A, B, C and logically equivalent',
do you mean 
`(not n1.queried) or (not n2.queried) or (n1.label == n2.label)`
 is equivalent with
`(not n1.queried) or (not n2.queried) or (n1.queried and n2.queried and n1.label == n2.label)`?

**Comment by jifanz** [comment]
Yes

**Comment by pengxiao-song** [comment]
> Yes

Thank you for your patience. 

Perhaps this is inappropriate, because we shouldn't use the label of instances which has not been queried until this AL loop in advance. 

If I made any mistake, please correct me.

**Comment by jifanz** [comment]
Which AL loop are you referring to? And do you mean until AL loop finishes?

**Comment by pengxiao-song** [comment]
> Which AL loop are you referring to? And do you mean until AL loop finishes?

Yes. You shouldn't use labels of instances which has not been queried.

In `(not n1.queried) or (not n2.queried) or (n1.label == n2.label)`, the output of this clause is True when `n1.label == n2.label` but maybe n1 or n2 has not been queried.

**Comment by jifanz** [comment]
I just told you
`(not n1.queried) or (not n2.queried) or (n1.label == n2.label)`
and
`(not n1.queried) or (not n2.queried) or (n1.queried and n2.queried and n1.label == n2.label) `
are logically equivalent statements…

Please, write out a truth table. Here’s how to write out a truth table if you don’t know how: https://en.m.wikipedia.org/wiki/Truth_table. Before you accusing me again, please find a concrete counter-example where the code is not equivalent with what you think it’s doing. It is very disrespectful to keep accusing me of doing something wrong, when you could have easily done your due diligence before posting.

**Comment by pengxiao-song** [comment]
> I just told you `(not n1.queried) or (not n2.queried) or (n1.label == n2.label)` and `(not n1.queried) or (not n2.queried) or (n1.queried and n2.queried and n1.label == n2.label) ` are logically equivalent statements…
> 
> Please, write out a truth table. Here’s how to write out a truth table if you don’t know how: https://en.m.wikipedia.org/wiki/Truth_table. Before you accusing me again, please find a concrete counter-example where the code is not equivalent with what you think it’s doing. It is very disrespectful to keep accusing me of doing something wrong, when you could have easily done your due diligence before posting.


I am not mean to bother you. You always underline this is logically equivalent, but I think this is never a logic problem.

<!DOCTYPE html>

n1.label==n2.label | n1.queried | n2.queried | (not n1.queried) or (not n2.queried) or (n1.label == n2.label) | (n1.label == n2.label) or (not n1.queried) or (not n2.queried)
-- | -- | -- | -- | --
True | False | False | True | True

Just like this, even if both n1 and n2 have not been queried, n1.label and n2.label is still True, and the output of 'if' statement is True. However, in this condition, how could you know labels of n1 and n2 to judge n1.label == n2.label ?

**Comment by jifanz** [comment]
`(not n1.queried) or (not n2.queried) or (n1.queried and n2.queried and n1.label == n2.label)` will also return True in this case. I don’t see a problem. Find me a case where the two lines of code produce different results. Otherwise, it means they are equivalent lines of code. Therefore, they are equivalent ways of expressing the same idea.
